import streamlit as st
import google.generativeai as genai
from urllib.parse import quote
import requests
from PIL import Image
from io import BytesIO

st.set_page_config(
    page_title="Multimodal Manufacturing Creator",
    page_icon="🏭",
    layout="wide"
)

st.title("Multimodal Manufacturing Creator")
st.caption("Enter a manufacturing concept → get a technical narrative (LLM) + visual prototype (Image Generation)")

# Sidebar
with st.sidebar:
    st.markdown("## ⚙️ Settings")
    api_key = st.text_input("Gemini API Key", type="password", help="Stored only for this session.")
    st.markdown("---")
    st.markdown("**Visual Style**")
    style = st.selectbox("Image style", [
        "Technical blueprint, engineering diagram",
        "Photorealistic industrial photography",
        "3D render, product prototype",
        "Schematic exploded view, labelled parts"
    ])
    st.markdown("---")
    st.markdown("**How it works**")
    st.markdown("1. Enter a manufacturing concept")
    st.markdown("2. **Gemini LLM** → technical narrative")
    st.markdown("3. **Flux Image Model** → visual prototype")
    st.markdown("---")
    st.markdown("**Group 01D6**")

# Example concepts
examples = [
    "CNC milling machine for aerospace precision parts",
    "Robotic welding arm for automotive assembly line",
    "Injection molding press for plastic enclosures",
    "Conveyor belt sorting system with vision sensors",
    "Industrial 3D printer for metal components",
    "Automated PCB soldering machine for electronics"
]

st.subheader("Manufacturing Concept")
col_input, col_example = st.columns([3, 1])

with col_input:
    concept = st.text_input(
        "concept",
        placeholder="e.g. Robotic welding arm for automotive assembly",
        label_visibility="collapsed"
    )

with col_example:
    selected = st.selectbox("Or pick an example", ["— select —"] + examples, label_visibility="collapsed")
    if selected != "— select —":
        concept = selected

generate = st.button(" Generate", type="primary", disabled=not api_key.strip())

if not api_key.strip():
    st.info("👈 Enter your Gemini API key in the sidebar to get started.")

elif generate and concept:
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("📝 Technical Narrative")
        st.caption("Model: Gemini 2.5 Flash (Text-to-Text)")
        with st.spinner("Generating description..."):
            try:
                genai.configure(api_key=api_key)
                model = genai.GenerativeModel("gemini-2.5-flash")
                prompt = f"""You are a senior manufacturing engineer and technical writer.

For the manufacturing concept: "{concept}"

Write a structured technical description with these exact sections:
1. **Overview** — What it is and its primary purpose (2-3 sentences)
2. **Working Principle** — How it operates step by step (3-4 sentences)
3. **Key Components** — List 4-5 main components with one-line descriptions
4. **Manufacturing Application** — Industry use cases (2-3 sentences)
5. **Advantages** — 3 key benefits in bullet points

Keep it professional, concise, and educational. Total: ~200 words."""

                response = model.generate_content(prompt)
                st.markdown(response.text)
                st.success("✅ Generated by Gemini 2.5 Flash")

            except Exception as e:
                st.error(f"LLM Error: {e}")

    with col2:
        st.subheader("🖼️ Visual Prototype")
        st.caption("Model: Flux via Pollinations.ai (Text-to-Image)")
        with st.spinner("Generating image..."):
            try:
                img_prompt = f"{concept}, {style}, manufacturing, industrial, high detail, professional technical illustration, white background"
                encoded = quote(img_prompt)
                img_url = f"https://image.pollinations.ai/prompt/{encoded}?width=800&height=600&model=flux&nologo=true&seed=42"
                response = requests.get(img_url, timeout=60)
                img = Image.open(BytesIO(response.content))
                st.image(img, use_container_width=True)
                st.success("✅ Generated by Flux (Pollinations.ai)")
                with st.expander("View image prompt sent"):
                    st.code(img_prompt)

            except Exception as e:
                st.error(f"Image Error: {e}")

# Workflow always visible at bottom
st.divider()
st.subheader("Multimodal GenAI Workflow")

# Row 1 - single input
col_space1, col_center, col_space2 = st.columns([1, 2, 1])
with col_center:
    st.info("💬 **USER INPUT**\n\nSingle manufacturing concept prompt")

# Row 2 - splits into two (Centered using HTML with 15px vertical padding)
st.markdown("<div style='text-align: center; padding: 15px 0;'>⬇️ same prompt feeds both models ⬇️</div>", unsafe_allow_html=True)

col1, col_mid, col2 = st.columns([2, 0.2, 2])
with col1:
    st.success("🤖 **MODEL 1 — Text-to-Text**\n\nGemini 2.5 Flash (LLM)\n\nGenerates structured technical narrative")
with col2:
    st.warning("🎨 **MODEL 2 — Text-to-Image**\n\nFlux via Pollinations.ai\n\nGenerates visual prototype / illustration")

# Row 3 - arrows (Using the exact same column ratio to perfectly center them over the outputs)
arr1, arr_mid, arr2 = st.columns([2, 0.2, 2])
with arr1:
    st.markdown("<div style='text-align: center; padding: 15px 0;'>⬇️</div>", unsafe_allow_html=True)
with arr2:
    st.markdown("<div style='text-align: center; padding: 15px 0;'>⬇️</div>", unsafe_allow_html=True)

# Row 4 - outputs
col3, col_mid2, col4 = st.columns([2, 0.2, 2])
with col3:
    st.error("📄 **OUTPUT 1 — Technical Narrative**\n\nOverview · Working Principle · Components · Applications · Advantages")
with col4:
    st.error("🖼️ **OUTPUT 2 — Visual Prototype**\n\nAI-generated engineering illustration of the concept")

st.divider()
st.caption("**Multimodal** = one prompt → two different AI model types → richer combined output than either model alone")